apiVersion: v1
kind: ConfigMap
metadata:
  name: asset-management-config
data:
  datasource.url: jdbc:oracle:thin:@oraclexe.asset-management:1521:XE
  funds.datasource.username: FUNDS
  funds.datasource.password: "P4$$word123"