apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oradata-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: oradata
  volumeName: oradata-pv