apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
spec:
  containers:
    - name: dnsutils
      image: tutum/dnsutils:latest
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: oradata
          mountPath: /opt/oracle/oradata
        - name: orasetup
          mountPath: /opt/oracle/orasetup
  restartPolicy: Always
  volumes:
    - name: oradata
      persistentVolumeClaim:
        claimName: oradata-pvc
    - name: orasetup
      persistentVolumeClaim:
        claimName: orasetup-pvc