apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
commonLabels:
  env: local
resources:
  - data-persistent-volume.yaml
  - data-persistent-volume-claim.yaml
#  - dnsutils.yaml
  - oraclexe.yaml
patchesStrategicMerge:
  - config.yaml
  - funds.yaml