apiVersion: v1
kind: Service
metadata:
  name: oraclexe
spec:
  clusterIP: None
  ports:
    - name: listener
      protocol: TCP
      port: 1521
      targetPort: 51521
  selector:
    role: oraclexe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oraclexe
  labels:
    role: oraclexe
spec:
  replicas: 1
  selector:
    matchLabels:
      role: oraclexe
  template:
    metadata:
      labels:
        role: oraclexe
    spec:
      containers:
        - name: oraclexe
          image: oracle/database:18.4.0-xe
          env:
            - name: ORACLE_PWD
              value: "P4$$word123"
          resources:
            requests:
              memory: 2Gi
          ports:
            - containerPort: 1521
          readinessProbe:
            exec:
              command: [ "/bin/sh", "-c", "$ORACLE_BASE/checkDBStatus.sh" ]
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
          volumeMounts:
            - name: oradata
              mountPath: /opt/oracle/oradata
      terminationGracePeriodSeconds: 10
      volumes:
        - name: oradata
          persistentVolumeClaim:
            claimName: oradata-pvc