apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: asset-management
resources:
  - config.yaml
  - funds.yaml
images:
  - name: oraclexe
    newName: "oracle/database"
    newTag: 18.4.0-xe
  - name: funds
    newName: asset-management-funds
    newTag: 0.0.01-SNAPSHOT

